apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cd-listener
spec:
  serviceAccoountName: pipeline
  triggers:
  - bindings:
    - ref: cd-binding
    template:
      ref: cd-template
  